version: "3.3"
services:
  webcam:
    build: ./
    command: "python3 webcam.py"
    ports:
      - "3600:3600"
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - calcul-data:/calculAI_object_detection/videos 
      - /dev/video0:/dev/video0
      - /tmp/.X11-unix:/tmp/.X11-unix
    # networks:
    #   - calcul-default
    depends_on:
      - analysis
  calcul:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
   volumes:
      - .:/calculAI_object_detection
    # networks:
    #   - calcul-default

volumes:
  calcul-data:

# networks:
#   calcul-default: